# Data Visualization

Visualizing data is an area where R really shines.  We are going to again take a
split approach.  I will show some quick and easy graphics that we can produce 
with base R, but we won't spend anytime customizing them. Instead, we will move
on quickly to `ggplot2`, which is now (I have no data to back this up), the 
de-facto standard for visualizing data in R.  We have only a very short time to
spend on this, but hopefully it will provide enough of a foundation for future
learning.

## Lesson Outline:

- [Simple plots with base R](#Simple plots with base R)
- [Introduction to `ggplot2`](#Introduction to `ggplot2`)
- [Customizing `ggplot2` plots](#Customizing `ggplot2` plots)
- [Getting help with `ggplot2`](#Getting help with `ggplot2`)

## Lesson Exercises:
- [Exercise 4.1](#exercise-41)
- [Exercise 4.2](#exercise-42)

##Simple plots with base R

##Introduction to `ggplot2`

##Exercise 4.1
http://usepa.github.io/introR/2015/01/15/07-Visualize/#exercise-1

##Customizing `ggplot2` plots

##Exercise 4.2
http://usepa.github.io/introR/2015/01/15/07-Visualize/#exercise-2

##Getting help with `ggplot2`
